version: '3'
services:
  db:
    image: postgres
    container_name: patli 
    restart: always
    env_file:
      - ./server-pahtli/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
  web:
    build: ./server-pahtli
    env_file:
      - ./server-pahtli/.env
    volumes:
      - ./server-pahtli:/code
    ports:
      - "8000:8000"
    depends_on:
      - db  
    environment:
      - DEBUG=1  
volumes:
  postgres_data: