# Generated by Django 5.0.6 on 2024-09-22 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_paciente", models.CharField(max_length=100)),
                ("edad", models.IntegerField()),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "MASCULINO"), ("F", "FEMENINO")], max_length=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cardio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_dolor_pecho",
                    models.CharField(
                        choices=[
                            ("ASY", "ASINTOMATICO"),
                            ("NAP", "SIN DOLOR ANGINAL"),
                            ("ATA", "ANGINA ATIPICA"),
                            ("TA", "ANGINA TIPICA"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "presion_arterial_reposo",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("colesterol", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "azucar_sangre_ayuno",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "electrogardiograma_reposo",
                    models.CharField(
                        choices=[
                            ("NORMAL", "NORMAL"),
                            ("ST", "ANOMALIA DEL SEGMENTO ST"),
                            ("LVH", "HIPERTROFIA VENTRICULAR IZQUIERDA (LVH)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("frecuencia_cardiaca_maxima", models.IntegerField()),
                (
                    "angina_por_ejercicio",
                    models.CharField(choices=[("S", "SI"), ("N", "NO")], max_length=5),
                ),
                ("viejo_pico_ST", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "st_slope",
                    models.CharField(
                        choices=[
                            ("up", "ASCENDENTE"),
                            ("flat", "PLANO"),
                            ("down", "DESCENDENTE"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enfermedadcardio.paciente",
                    ),
                ),
            ],
        ),
    ]
