# Generated by Django 5.0.6 on 2024-09-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enfermedadcardio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardio",
            name="angina_por_ejercicio",
            field=models.IntegerField(choices=[(1, "SI"), (0, "NO")]),
        ),
        migrations.AlterField(
            model_name="cardio",
            name="electrogardiograma_reposo",
            field=models.IntegerField(
                choices=[
                    (1, "NORMAL"),
                    (0, "ANOMALIA DEL SEGMENTO ST"),
                    (2, "HIPERTROFIA VENTRICULAR IZQUIERDA (LVH)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cardio",
            name="st_slope",
            field=models.IntegerField(
                choices=[(2, "ASCENDENTE"), (1, "PLANO"), (0, "DESCENDENTE")],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="cardio",
            name="tipo_dolor_pecho",
            field=models.IntegerField(
                choices=[
                    (0, "ASINTOMATICO"),
                    (2, "SIN DOLOR ANGINAL"),
                    (1, "ANGINA ATIPICA"),
                    (3, "ANGINA TIPICA"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="genero",
            field=models.IntegerField(choices=[(1, "MASCULINO"), (0, "FEMENINO")]),
        ),
    ]
