# Generated by Django 5.0.6 on 2024-09-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enfermedadcardio", "0004_alter_paciente_nombre_paciente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardio",
            name="tipo_dolor_pecho",
            field=models.IntegerField(
                choices=[
                    ("ASINTOMATICO", 0),
                    ("SIN DOLOR ANGINAL", 2),
                    ("ANGINA ATIPICA", 1),
                    ("ANGINA TIPICA", 3),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="genero",
            field=models.IntegerField(choices=[("MASCULINO", 1), ("FEMENINO", 0)]),
        ),
    ]
