# Generated by Django 5.0.6 on 2024-10-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "enfermedadcardio",
            "0006_alter_cardio_tipo_dolor_pecho_alter_paciente_genero",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cardio",
            name="target",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nombre_paciente",
            field=models.CharField(max_length=100),
        ),
    ]
