# Generated by Django 5.0.6 on 2024-10-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enfermedadcardio", "0007_cardio_target_alter_paciente_nombre_paciente"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardio",
            name="azucar_sangre_cat",
            field=models.IntegerField(default=0),
        ),
    ]
